export const GET_USERS = "GET_USERS";
export const GET_DETAIL_EVENT_REQUESTED = "GET_DETAIL_EVENT_REQUESTED";
export const GET_DETAIL_EVENT_SUCCESS = "GET_DETAIL_EVENT_SUCCESS";
export const GET_DETAIL_EVENT_FAILED = "GET_DETAIL_EVENT_FAILED";
